service: poc-ci-cd-serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  example:
    handler: src/handlers/handler.example
    events:
      - httpApi:
          path: example-test
          method: GET
