service: project-ci-cd-severless

frameworkVersion: '3.30.1'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  example:
    handler: src/handlers/handler.example
    events:
      - httpApi:
          path: example
          method: GET
