service: poc-ci-cd-serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    URL_API: ${env:URL_API}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  example:
    handler: src/handlers/handler.example
    events:
      - httpApi:
          path: example-test
          method: GET
