name: CI(continuous integration)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: ESLint
        run: yarn run lint

      - name: Run all tests
        run: yarn test
